### PR TITLE
Added System-Based LookAndFeel

### PR DESCRIPTION
**Pull request by RoiEXLab**
Changed LookAndFeel according to the host System

### CODE REVIEW

**Comment by KovuTheHusky** [comment]
Thank you! I didn't realize this affected Save and Open dialogs since it didn't change anything on OS X. Checked on Windows and it look much better.

**Comment by RoiEXLab** [comment]
I have to thank you for your awesome Library ^^
I will use it for a tool to create source engine maps using your minecraft
world(also available on github)
And yes... I recognized on Linux and Mac it doesn't change at all. Another
option would be to write an own look and feel using xml... Don't ask me how
just heard it is possible...
Another Question... I'm having trouble reading minecraft region
files(getting cast errors because of Tag_END without tag compounds) Could
you give me a hint?
Regards RoiEX
Am 12.01.2016 9:14 nachm. schrieb "Kevin Breslin" <notifications@github.com

**Comment by KovuTheHusky** [comment]
Region files aren't just NBT data, they're a file that has a header (see http://minecraft.gamepedia.com/Region_file_format on the wiki) and then a bunch of chunk data (see http://minecraft.gamepedia.com/Chunk_format on the wiki). I don't have support for reading the header yet. I'll open an issue about it and start working on it soon. If you have any other suggestions, open an issue. I'd love to work on this project more.

**Comment by RoiEXLab** [comment]
Thank you :-) I forgot about the header thing... I will try to help you as
best as I can(I'm not very experienced in reading binary files).
The faster you get this done, the faster I can finish my own project 😁
Am 12.01.2016 9:40 nachm. schrieb "Kevin Breslin" <notifications@github.com

**Comment by RoiEXLab** [comment]
Man, you're just awesome.
a HUGE THANK YOU to you and your afford to update your Library
I just can't believe how fast you got this done (I don't need the write to
mca feature so it's enough for me)

2016-01-12 21:46 GMT+01:00 Robin T. <robin.textor@gmail.com>:

**Pull request merged**
